### ISSUE TITLE
Is it installable on an Raspberry 4  with ubuntu 22.04

### ISSUE THREAD

**Issue by ChopperHop** [jjziets/vastai_analytics_dasboard#3]
This is a dashboard I want!  Can I install it? And help it make it better? Or is it a dead case?
Greets Chris

**Comment by jjziets** [comment]
i honestly have not tried it. it would be great to get working. but there are a few drawbacks to my design. so I'm not so sure its worth the effort to set this up. it gets very slow on a PC over time. in fact so slow that I no longer use it.

**Comment by ChopperHop** [comment]
Well  I gone a give it a try.
I'm an old small miner new on VAST.ai   spending my time. Not an programmer
more hardware.
I'll keep You in touch

Op do 8 dec. 2022 om 18:35 schreef Etherion ***@***.***>:
